
[package]
name = "whitehat-client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.16.15"
solana-client = "1.16.15"
solana-program = "1.16.15"
borsh = "0.9.0"
serde = { version = "1.0.125", features = ["derive"] }
bs58 = "0.5.0"
rand = "0.7.3"
